- name: Install and config apache2
  hosts: all
  roles:
    - { role: httpd , when: ansible_distribution == "CentOS"}
    - { role: apache2 , when: ansible_distribution == "Ubuntu" or ansible_os_family == "Suse"}
